name: helm-test
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'charts/tf-controller/**'
      - '.github/workflows/helm-test.yaml'

permissions: read-all

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5.0
        with:
          version: latest

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'

      - name: Build the tf-controller container image
        run: |
          make docker-buildx MANAGER_IMG=test/tf-controller RUNNER_IMG=test/tf-runner TAG=ct \
            BUILD_ARGS="--load"
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Load test images into KIND
        run: |
          kind load docker-image --name=chart-testing test/tf-controller:ct
          kind load docker-image --name=chart-testing test/tf-runner:ct
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Flux CLI
        uses: fluxcd/flux2/action@3b42b200d376430f0e24d35f1a600447d92da531 # main
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Source controller
        run: flux install --components=source-controller
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
