name: test
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "charts/**"
      - "docs/**"
      - "hack/**"
      - "logos/**"
      - "rfcs/**"
      - "tools/**"
      - "*.md"
  push:
    branches:
      - main

permissions:
  contents: read # for actions/checkout to fetch code

jobs:
  test-1x-2x:
    name: "Controller Tests: 10->29"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0000[12]"
  test-3x-5x:
    name: "Controller Tests: 30->59"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0000[345]"
  test-6x-9x:
    name: "Controller Tests: 60->99"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0000[6789]"
  test-1xx:
    name: "Controller Tests: 1xx"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0001"
  test-2xx:
    name: "Controller Tests: 2xx"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0002"
  test-3xx:
    name: "Controller Tests: 3xx"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0003"
  test-99xx:
    name: "Controller Tests: 99xx"
    uses: ./.github/workflows/targeted-test.yaml
    with:
      pattern: "^Test_0099"
  non-numbered:
    name: "Controller Tests: Non-numbered"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.20.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Terraform
        run: |
          export TF_VERSION=1.3.9
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -q terraform_${TF_VERSION}_linux_amd64.zip
          mv terraform $(which terraform)
          terraform --version
      - name: Setup Kustomize
        if: "!github.event.pull_request.head.repo.fork"
        uses: fluxcd/pkg/actions/kustomize@6c0b4426ba7809a9406c1a4e07aa4be4984ea72f # main
      - name: Run tests
        run: |
          make install-envtest
          make normal-controller-test
  internal:
    name: "Internal Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.20.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Terraform
        run: |
          export TF_VERSION=1.3.9
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -q terraform_${TF_VERSION}_linux_amd64.zip
          mv terraform $(which terraform)
          terraform --version
      - name: Setup Kustomize
        if: "!github.event.pull_request.head.repo.fork"
        uses: fluxcd/pkg/actions/kustomize@6c0b4426ba7809a9406c1a4e07aa4be4984ea72f # main
      - name: Run tests
        run: |
          make install-envtest
          make test-internal
